name: teste_app
description: >
  Sistema de Investimento em Rede XITIKE - Aplicativo móvel para gerenciamento 
  de investimentos em rede com sistema hierárquico de bonificações
publish_to: "none"
version: 1.0.0+1
homepage: https://xitike.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Pacotes principais
  http: ^1.2.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.2.2

  # State management e DI
  provider: ^6.0.5
  get_it: ^8.2.0

  # Internacionalização
  flutter_localizations:
    sdk: flutter

  # Logging profissional (para substituir print)
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/pesa.jpg
    - assets/logo.png
